UMC-TOMORROW/Tomorrow-Backend

src/main/java/com/umc/tomorrow/global/config/SecurityConfig.java, src/main/resources/application.yml
- close #이슈번호
- close #1
- 로그인에 필요한 기본 Security 설정 및 네이버 로그인 관련 환경변수를 설정하였습니다.
- 로컬 개발시에 cofigurations에 해당하는 값 적용해서 실행해주세요!
=> Feat/security setting#1

build.gradle, docker/dokerFile, src/main/java/com/umc/tomorrow/global/config/CorsMvcConfig.java, src/main/java/com/umc/tomorrow/global/config/SecurityConfig.java, src/main/java/com/umc/tomorrow/global/dto/CustomOAuth2User.java, src/main/java/com/umc/tomorrow/global/dto/GoogleResponse.java, src/main/java/com/umc/tomorrow/global/dto/NaverResponse.java, src/main/java/com/umc/tomorrow/global/dto/OAuth2Response.java, src/main/java/com/umc/tomorrow/global/dto/UserDTO.java, src/main/java/com/umc/tomorrow/global/entity/UserEntity.java, src/main/java/com/umc/tomorrow/global/jwt/JWTFilter.java, src/main/java/com/umc/tomorrow/global/jwt/JWTUtil.java, src/main/java/com/umc/tomorrow/global/oauth2/CustomSuccessHandler.java, src/main/java/com/umc/tomorrow/global/repository/UserRepository.java, src/main/java/com/umc/tomorrow/global/service/CustomOAuth2UserService.java, src/main/resources/application-local.yml, src/main/resources/application.yml
- close #8
- jwt발급 및 검증, 구글 로그인 구현
- 코딩 실수로 commit이 1개 밖에 없습니다..
- jwt발급은 확인했는데 제가 놓친 부분이 있다면 알려주시면 감사하겠습니다.
=> Feat: JWT발급 및 구글 로그인 구현#8

src/main/java/com/umc/tomorrow/domain/careertalk/controller/CareertalkController.java, src/main/java/com/umc/tomorrow/domain/careertalk/dto/request/CreateCareertalkRequestDto.java, src/main/java/com/umc/tomorrow/domain/careertalk/dto/response/CreateCareertalkResponseDto.java, src/main/java/com/umc/tomorrow/domain/careertalk/dto/response/GetCareertalkListResponseDto.java, src/main/java/com/umc/tomorrow/domain/careertalk/dto/response/GetCareertalkResponseDto.java, src/main/java/com/umc/tomorrow/domain/careertalk/entity/Careertalk.java, src/main/java/com/umc/tomorrow/domain/careertalk/repository/CareertalkRepository.java, src/main/java/com/umc/tomorrow/domain/careertalk/service/command/CareertalkCommandService.java, src/main/java/com/umc/tomorrow/domain/careertalk/service/command/CareertalkCommandServiceImpl.java, src/main/java/com/umc/tomorrow/domain/careertalk/service/query/CareertalkQueryService.java, src/main/java/com/umc/tomorrow/domain/careertalk/service/query/CareertalkQueryServiceImpl.java
- close #이슈번호
- 커리어톡 게시글 생성 api 구현
- 커리어톡 목록 조회(무한 스크롤) api 구현
- 커리어톡 상세 조회 api 구현
- swagger를 이용한 api 테스트 진행
- 없습니다.
- <img width="684" height="346" alt="스크린샷 2025-07-10 오후 10 32 07" src="https://github.com/user-attachments/assets/c99b7421-3d0f-4941-ba85-3e04c29456cd" />
- <img width="632" height="369" alt="스크린샷 2025-07-11 오전 2 57 52" src="https://github.com/user-attachments/assets/36fa8c70-46ae-4b4f-b8b9-8d7580d41db6" />
- <img width="1011" height="683" alt="스크린샷 2025-07-10 오후 9 37 34" src="https://github.com/user-attachments/assets/200ac376-4837-4e2a-b82c-060aea2f8004" />
- <img width="639" height="425" alt="스크린샷 2025-07-11 오전 2 57 06" …
=> Feat/careertalk create and select#11

src/main/java/com/umc/tomorrow/domain/auth/controller/AuthController.java, src/main/java/com/umc/tomorrow/domain/auth/jwt/JWTFilter.java, src/main/java/com/umc/tomorrow/domain/auth/jwt/JWTUtil.java, src/main/java/com/umc/tomorrow/domain/auth/security/CustomOAuth2User.java, src/main/java/com/umc/tomorrow/domain/auth/security/CustomSuccessHandler.java, src/main/java/com/umc/tomorrow/domain/auth/service/CustomOAuth2UserService.java, src/main/java/com/umc/tomorrow/domain/member/dto/UserConverter.java, src/main/java/com/umc/tomorrow/domain/member/dto/UserDTO.java, src/main/java/com/umc/tomorrow/domain/member/entity/User.java, src/main/java/com/umc/tomorrow/domain/member/enums/Gender.java, src/main/java/com/umc/tomorrow/domain/member/service/MemberService.java, src/main/resources/validation.properties
- close #이슈번호
- User 엔티티 생성/저장 시 createdAt, updatedAt 필드 null 방지
- setter 대신 builder 로 변경
- UserConverter 추가
- setter 대신 builder로 수정했습니다.
=> Feat/member profile#7

.github/ISSUE_TEMPLATE/fix_bug_report.yml
- close #이슈번호
- FIX 오류 템플릿 만들고 수정했습니다.
=> Update/fix_bug_report.yml 오류 FIX pr 템플릿 만들었습니다.

.gitignore, src/main/resources/application-dev.yml
- close #이슈번호
- AWS EC2 서버에 Spring Boot 애플리케이션 배포, 이를 위한 yml 파일 일부 수정
- AWS EC2 서버에 Spring Boot 애플리케이션 배포
=> Fix/EC2 setting을 위한 yml 파일 수정

src/main/java/com/umc/tomorrow/domain/auth/security/CustomSuccessHandler.java, src/main/java/com/umc/tomorrow/domain/careertalk/dto/response/GetCareertalkResponseDto.java, src/main/java/com/umc/tomorrow/domain/careertalk/service/query/CareertalkQueryServiceImpl.java, src/main/java/com/umc/tomorrow/domain/member/repository/UserRepository.java, src/main/java/com/umc/tomorrow/global/common/base/BaseResponse.java
- close #33 
- 커리어톡 단일 조회 시 필드 누락 수정
- 소셜 로그인 시 중복된 유저 삽입 버그 수정
- 삭제 응답 상태 코드 변경
- 실행되는지 로컬에서 실행 부탁드립니다!!
=> Fix/social login refactoring#33

.github/workflows/ci-cd.yml, docker/docker-compose.yml, src/main/java/com/umc/tomorrow/domain/application/converter/ApplicationConverter.java
- 도거 컴포즈 파일 수정하고 ci-cd.yml파일 추가하였습니다.
=> Feat: docker, ci-cd 추가

src/main/java/com/umc/tomorrow/domain/application/converter/ApplicationConverter.java, src/main/java/com/umc/tomorrow/domain/resume/entity/Experience.java, src/main/java/com/umc/tomorrow/domain/resume/entity/Resume.java
- close #59 
- Resume 엔티티에 experiences 필드 및 연관 매핑 추가
- Experience 엔티티에 description 필드 추가
- ApplicationConverter 내 getExperiences(), getDescription() 관련 오류 해결
related to #59
- develop pull받았더니 오류 나서 고쳤습니다.
=> fix: 지원서 상세 조회 시 경험(Experience) 필드 관련 오류 수정

.github/workflows/ci-cd.yml, docker/Dockerfile
=> Chore: 배포를 위한 설정 변경

src/main/java/com/umc/tomorrow/domain/temp/PingController.java
=> Chore: 배포 확인을 위한 api 테스트

src/main/java/com/umc/tomorrow/domain/temp/PingController.java, src/main/java/com/umc/tomorrow/global/config/SecurityConfig.java
=> Chore: 배포 확인을 위한 테스트 api 추가 및 swagger 경로 설정 변경

src/main/java/com/umc/tomorrow/global/config/CorsMvcConfig.java, src/main/java/com/umc/tomorrow/global/config/SecurityConfig.java
=> Chore: 배포 확인을 위한 테스트 api 경로 변경 및 cors 설정 변경

src/main/java/com/umc/tomorrow/domain/application/entity/Application.java
=> fix: 중복된 필드 제거

build.gradle, src/main/java/com/umc/tomorrow/domain/Image/controller/S3Controller.java, src/main/java/com/umc/tomorrow/domain/Image/s3/S3Uploader.java, src/main/java/com/umc/tomorrow/domain/application/service/command/ApplicationService.java, src/main/java/com/umc/tomorrow/global/config/AmazonConfig.java, src/main/resources/application.yml
- close #88 
- docker 설정 변경 및 Cors에러 변경
=> Chore/swagger and cors refactoring#88

src/main/resources/application.yml
=> Fix : 메트릭 설정 변경

src/main/java/com/umc/tomorrow/global/config/SecurityConfig.java, src/main/resources/application.yml
=> Fix : swagger설정을 위한 서버 공통 설정

src/main/java/com/umc/tomorrow/domain/application/service/command/ApplicationService.java
- close #이슈번호
- 빌드 오류로 배포가 안돼서 수정 후 다시 merge 합니다.
=> Fix: ci-cd 빌드 오류 수정

src/main/java/com/umc/tomorrow/domain/preferences/entity/Preference.java
=> Fix: 선호도 엔티티 기본 생성자 어노테이션 추가

src/main/java/com/umc/tomorrow/domain/resume/certificate/entity/Certificate.java, src/main/java/com/umc/tomorrow/domain/resume/converter/ResumeConverter.java, src/main/java/com/umc/tomorrow/domain/resume/dto/request/ResumeSaveRequestDTO.java
- close #111 
- certificate entity에 createdAt, updatedAt 필드 추가
- ResumeSaveRequestDTO수정
- ResumeConverter 수정 - toEntity 로직 다시
- <img width="542" height="317" alt="image" src="https://github.com/user-attachments/assets/646ce55f-111e-4ca2-a58b-773a13320967" />
=> Fix : 이력서 저장 부분 수정 

src/main/java/com/umc/tomorrow/domain/review/controller/ReviewController.java, src/main/java/com/umc/tomorrow/domain/review/dto/ReviewConverter.java, src/main/java/com/umc/tomorrow/domain/review/dto/ReviewRequestDTO.java, src/main/resources/validation.properties
- close #114 
- validation추가했습니다. (리뷰는 0~점사이만 가능하고, 리뷰 내용은 필수입니다.)
- swagger 캡쳐본입니다.
=> Fix : 리뷰 - validation 추가

src/main/java/com/umc/tomorrow/domain/application/converter/ApplicationConverter.java, src/main/java/com/umc/tomorrow/domain/certificate/controller/CertificateController.java, src/main/java/com/umc/tomorrow/domain/certificate/dto/response/CertificateResponse.java, src/main/java/com/umc/tomorrow/domain/certificate/entity/Certificate.java, src/main/java/com/umc/tomorrow/domain/certificate/exception/CertificateException.java, src/main/java/com/umc/tomorrow/domain/certificate/exception/code/CertificateErrorStatus.java, src/main/java/com/umc/tomorrow/domain/certificate/repository/CertificateRepository.java, src/main/java/com/umc/tomorrow/domain/certificate/service/command/CertificateCommandService.java, src/main/java/com/umc/tomorrow/domain/certificate/service/command/CertificateCommandServiceImpl.java, src/main/java/com/umc/tomorrow/domain/resume/converter/ResumeConverter.java, src/main/java/com/umc/tomorrow/domain/resume/entity/Resume.java, src/main/java/com/umc/tomorrow/domain/resume/exception/code/ResumeErrorStatus.java
- close #117 
- 자격증에 관한 검증 로직을 추가했습니다!
- 없습니다.
=> Fix: 자격증 관련 로직 수정

src/main/java/com/umc/tomorrow/domain/job/controller/command/JobCommandController.java, src/main/java/com/umc/tomorrow/domain/job/converter/JobConverter.java, src/main/java/com/umc/tomorrow/domain/job/dto/request/JobRequestDTO.java, src/main/java/com/umc/tomorrow/global/common/exception/RestApiException.java
- close #이슈번호
- 일자리 등록 시 이미지를 추가할 수 있는 기능을 구현하였습니다.
=> Feat: 일자리 이미지 추가

docker/Dockerfile, src/main/resources/application.yml
- close #157
- db에 데이터가 삽입될때 서울시간대로 삽입되기 위해서 Dockerfile과 aplication.yml 설정을 추가하였습니다.
- 없습니다.
=> Chore: timezone 서울 시간으로 변경

src/main/java/com/umc/tomorrow/domain/application/controller/command/ApplicationController.java, src/main/java/com/umc/tomorrow/domain/application/converter/ApplicationConverter.java, src/main/java/com/umc/tomorrow/domain/application/entity/Application.java, src/main/java/com/umc/tomorrow/domain/application/enums/ApplicationStatus.java, src/main/java/com/umc/tomorrow/domain/application/exception/code/ApplicationErrorStatus.java, src/main/java/com/umc/tomorrow/domain/application/repository/ApplicationRepository.java, src/main/java/com/umc/tomorrow/domain/application/service/command/ApplicationCommandService.java, src/main/java/com/umc/tomorrow/global/common/exception/ExceptionAdvice.java
=> Fix :  GET /api/v1/posts/17/applicants?status=closed/open api 수정

docker/Dockerfile, src/main/java/com/umc/tomorrow/domain/careertalk/service/query/CareertalkQueryServiceImpl.java, src/main/java/com/umc/tomorrow/global/infrastructure/s3/S3Uploader.java
- close #이슈번호
- 배포된 환경에서 발생한 여러 에러를 수정합니다.
=> Fix/swagger update/#175

src/main/java/com/umc/tomorrow/domain/application/controller/command/ApplicationController.java, src/main/java/com/umc/tomorrow/domain/application/service/command/ApplicationCommandService.java
- close #182 
- 이력서 부분 모든 API가 Application ID 기반으로 돌아가도록 수정했습니다.
- postId -> jobId로 수
=> Fix : postId -> jobId, api 통일

src/main/java/com/umc/tomorrow/domain/job/service/command/JobCommandServiceImpl.java
=> Fix: TEST RE merge

src/main/java/com/umc/tomorrow/domain/job/service/query/JobQueryServiceImpl.java
=> Fix: 필요없는 로직 개선
